.\" Manpage for nomcash-gtk


.TH nomcash-gtk 1 "March 21, 2014" "0.1" "nomcash-gtk man page"


.SH NAME

nomcash-gtk \- a program to keep an eye on your cash


.SH SYNOPSIS

.B nomcash-gtk 
.RI [ OPTION ]


.SH DESCRIPTION

.B nomcash-gtk 
supports you protocolling your money movements. Be it hard or electronic cash, 
.B nomcash-gtk
helps you categorize investments, incomings, borrowings and everything else that can happen to your financial means.
.PP
The main documentation can be found in the 
.B nomcash-gtk
doc folder located in /usr/share/doc/nomcash and as tooltips in the GTK application.


.SH OPTIONS

.B nomcash-gtk
doesn't take that much options, since it is a GTK+ application. You can let it tell you its version number but that's about it.
.TP
.B \-v
Output version number and quit.


.SH AUTHOR
.B nomcash-gtk
was written by Yann Büchau <nobodyinperson@gmx.de>.
